language: cpp

os:
  - windows

before_install:
  - wget "https://download.qt.io/archive/online_installers/3.0/qt-unified-windows-x86-3.0.6-online.exe"

install:
  - #choco install wixtoolset
  - export LIST_PACKAGES=0 && export OUTPUT='C:\Qt' && export PACKAGES=qt.58.win64_msvc2015_64 && ./qt-unified-windows-x86-3.0.6-online.exe -v --script extract-qt.qs

script:
  - export CMAKE_PREFIX_PATH='C:\Qt\5.8.0\msvc2015_64'
  - mkdir build
  - cd build
  - cmake -D SYNERGY_ENTERPRISE=ON .
