language: cpp


env:
  global:
    - SYNERGY_ENTERPRISE=ON


jobs:
  include:

    - name: windows
      os: windows
      env:
        - DOWNLOAD_DIR='C:\downloads'
        - QT_INSTALL_DIR='C:\Qt'
        - QT_INSTALL_MSVC_SUBDIR='5.9.9\msvc2015_64'
        - QT_INSTALL_MSVC_PACKAGE='qt.qt5.599.win64_msvc2015_64'
        - CMAKE_PREFIX_PATH="${QT_INSTALL_DIR}\\${QT_INSTALL_MSVC_SUBDIR}"
      install:
        - |
          if ! [[ -d "$CMAKE_PREFIX_PATH" ]]; then
            QT_INSTALLER_PATH="${DOWNLOAD_DIR}\\qt-unified-windows-x86-online.exe"
            if ! [[ -f "$qt_installer_path" ]]; then
              ./travis_windows/download-qt-installer.sh
            else
              echo '### using cached Qt online installer'
            fi
            ./travis_windows/set-qt-account.sh
            ./travis_windows/install-qt.sh > ./install-qt.out
            if ! [[ -d "$CMAKE_PREFIX_PATH" ]]; then cat ./install-qt.out; fi
          else
            echo '### using cached installed Qt prerequisites'
          fi
      cache:
        directories:
          - "$DOWNLOAD_DIR"
          - "$QT_INSTALL_DIR"
      script:
        - echo '##### script -##### (jobs-include-windows-script) '

        - echo 'du -hs ~/*' && du -hs ~/*

        - mkdir 'build' && cd $_
        - |
          echo '# cmake generator'
          cmake -A x64 -T host=x64 .. || travis_terminate 1;
        - |
          echo '# cmake build'
          cmake --build .


    - name: linux
      os: linux
      dist: xenial
      addons:
        apt:
          sources:
            - sourceline: 'ppa:lopin/git-buildpackage-backports'
          packages:
            - cmake make g++
            - libssl-dev libsodium-dev libcurl4-openssl-dev libavahi-compat-libdnssd-dev libsystemd-dev
            - xorg-dev libx11-dev libgl1-mesa-glx libegl1-mesa
            - qtbase5-dev qtdeclarative5-dev libqt5svg5-dev
            - dpkg-dev git-buildpackage fakeroot debhelper
      script:
        - echo '##### script -##### (jobs-include-linux-script) '
        - |
          echo '# create debian/changelog from git history'
          gbp dch --ignore-branch
        - |
          echo '# make linux DEB package'
          dpkg-buildpackage -us -uc


after_script:
  - echo '##### after_script -#####'

  - mount

  - echo 'du -hs /c/Qt/*'
  - du -hs /c/Qt/*
  - echo 'du -hs ~/*'
  - du -hs ~/*

  - echo -n "# PWD=$PWD"
  - echo -n "# TRAVIS_BUILD_DIR=$TRAVIS_BUILD_DIR"

  - echo "# files $TRAVIS_BUILD_DIR/**:" ;
    find "$TRAVIS_BUILD_DIR" -print0 | xargs -0 ls -ld


after_failure:
  - echo '##### after_failure -#####'

  - echo -n "# PWD=$PWD"
  - echo -n "# TRAVIS_BUILD_DIR=$TRAVIS_BUILD_DIR"

  - cmake_output_log="${TRAVIS_BUILD_DIR}/build/CMakeFiles/CMakeOutput.log" ;
    echo "# $cmake_output_log :" ;
    cat "$cmake_output_log"
