language: cpp

#os:
#  - windows
#  - linux

matrix:
  include:
  - os: windows
    env: CMAKE_PREFIX_PATH='C:/Qt/5.8.0/msvc2015_64'
  - os: linux

dist: xenial

cache:
  directories:
    - /c/Qt

addons:
  apt:
    sources:
    - sourceline: 'ppa:lopin/git-buildpackage-backports'
    packages:
    - cmake make g++
    - libssl-dev libsodium-dev libcurl4-openssl-dev libavahi-compat-libdnssd-dev libsystemd-dev
    - xorg-dev libx11-dev libgl1-mesa-glx libegl1-mesa qtbase5-dev qtdeclarative5-dev libqt5svg5-dev
    - dpkg-dev git-buildpackage fakeroot

before_install:
  - if [[ "$TRAVIS_OS_NAME" = "linux" ]]; then echo 'linux1' ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then echo 'linux2' ; fi
  - if [[ $TRAVIS_OS_NAME == linux ]]; then echo 'linux3' ; fi
  - if [[ $TRAVIS_OS_NAME = linux ]]; then echo 'linux4' ; fi
  - if [[ "$TRAVIS_OS_NAME" = "linux" ]] && echo 'linux5'
  - if [ "$TRAVIS_OS_NAME" = "linux" ] && echo 'linux6'
  - echo "DONE before_install"

install:
  - echo "if ! [[ -d '/c/Qt' ]]; then mkdir '/c/Qt'; fi"
  - if [[ "$TRAVIS_OS_NAME" = "windows" && ! -d "/c/Qt/5.8.0/msvc2015_64" ]]; then
      qt_installer_filename='qt-unified-windows-x86-3.0.6-online.exe';
      qt_installer_automation_script='extract-qt.qs';
      echo "qt_installer_automation_script=$qt_installer_automation_script";
      wget "https://download.qt.io/archive/online_installers/3.0/${qt_installer_filename}";
      qt_install_cmd="${qt_installer_filename} -v --script ${qt_installer_automation_script} | grep '(QTCI|operation)'";
      echo "qt_install_cmd=$qt_install_cmd";
      OUTPUT='C:/Qt' && PACKAGES='qt.58.win64_msvc2015_64' && $qt_install_cmd;
    fi
  - echo "DONE install"

# LIST_PACKAGES=0 && OUTPUT='C:/Qt' && PACKAGES=qt.58.win64_msvc2015_64 && ./${qt_installer_filename} -v --script extract-qt.qs;
#  - if [[ $TRAVIS_OS_NAME = windows ]]; then
#      qt_installer_filename='qt-unified-windows-x86-3.0.6-online.exe';
#      wget "https://download.qt.io/archive/online_installers/3.0/$qt_installer_filename";
#      qt-unified-windows-x86-3.0.6-online.exe ;
#      chmod +x "$qt_installer_filename";
#      qt_install_cmd="${qt_installer_filename} -v --script './extract-qt.qs' | grep '\(QTCI\|operation\)'";
#      sh -c '$qt_installer_filename';
#    fi
#OUTPUT='C:/Qt' && PACKAGES='qt.58.win64_msvc2015_64' && $qt_install_cmd ;    # printf '#choco install wixtoolset;';
#     if [[ -z "$VERBOSE" ]]; then
#        qt_install_cmd="'./${qt_installer_filename}' --script './extract-qt.qs'";
#      else;
#        qt_install_cmd="'./${qt_installer_filename}' -v --script './extract-qt.qs' | grep '\(QTCI\|operation\)'";
#      fi;

#env:
#  - CMAKE_PREFIX_PATH='C:/Qt/5.8.0/msvc2015_64'

script:
  - if [[ $TRAVIS_OS_NAME = linux ]]; then gbp dch --ignore-branch ; fi
  - echo "CMAKE_PREFIX_PATH=$CMAKE_PREFIX_PATH"
  - pwd
  - ls -la
  - ls -l debian
  - if [[ $TRAVIS_OS_NAME = linux ]]; then dpkg-buildpackage -us -uc ; fi
  - mkdir build
  - cd build
  - cmake -D SYNERGY_ENTERPRISE=ON .. || ( cat 'CMakeFiles/CMakeOutput.log' ; false )
  - cmake --build .
  - echo "DONE script"

#  - mytmp=$(mktemp -d)
#  - cd $mytmp
#  - git clone https://github.com/loplex/synergy-core.git loplex/synergy-core
#  - cd loplex/synergy-core
#  - git checkout v1.x_lopin
#  - git checkout --detach
#  - gbp dch
