language: cpp

os:
  - windows
  - linux


matrix:
  include:

    - name: windows
      os: windows
      env:
        - QT_INSTALL_DIR='C:\Qt'
        - QT_INSTALL_PACKAGES='qt.qt5.599.win64_msvc2015_64'
        - CMAKE_PREFIX_PATH='C:\Qt\5.9.9\msvc2015_64'
        - CMAKE_GENERATOR_TOOLSET='v140,host=x64'
        - CMAKE_GENERATOR_PLATFORM='x64'
      install:
        - ./travis/windows-prepare-env.sh
      cache:
        directories:
          - /c/Qt
          - /c/qt_installer

    - name: linux
      os: linux
      dist: xenial
      addons:
        apt:
          sources:
            - sourceline: 'ppa:lopin/git-buildpackage-backports'
          packages:
            - cmake make g++
            - libssl-dev libsodium-dev libcurl4-openssl-dev libavahi-compat-libdnssd-dev libsystemd-dev
            - xorg-dev libx11-dev libgl1-mesa-glx libegl1-mesa
            - qtbase5-dev qtdeclarative5-dev libqt5svg5-dev
            - dpkg-dev git-buildpackage fakeroot debhelper
      script:
        - pwd && cd .. && ./travis/linux-create-deb-package.sh


script:
  - echo '# cmake generator' &&
    mkdir build && cd build &&
    cmake -DSYNERGY_ENTERPRISE=ON -DCMAKE_GENERATOR_PLATFORM=x64 -DCMAKE_VERBOSE_MAKEFILE=ON .. &&
    echo '# cmake build' &&
    cmake --build .
  - echo "# files $TRAVIS_BUILD_DIR/** :" ;
    cd "$TRAVIS_BUILD_DIR" ;
    find . -print0 | xargs -0 ls -ld


after_failure:
  - echo '# pwd:'
  - pwd
  - echo "# $TRAVIS_BUILD_DIR/build/CMakeFiles/CMakeOutput.log :"
  - cat "$TRAVIS_BUILD_DIR/build/CMakeFiles/CMakeOutput.log"
