language: cpp


env:
  global:
    - SYNERGY_ENTERPRISE=ON


before_install:
  - "tr_blue_title '##### before_install ######'"

  - |
    # util function for customizing travis build output log
    function travisfold() { echo -en "travis_fold:$1:$2\r" ; }
    function travisfoldblock() { travisfold start "$1" ; cat ; travisfold end "$1" ; }

    RED="\033[31;1m"; GREEN="\033[32;1m"; YELLOW="\033[33;1m"; BLUE="\033[34;1m"; RESET="\033[0m"
    function travis_color() { echo -e "${!1}" "${@:2}" ; }

    function travisfoldtitled() { { travis_color GREEN "$2" ; cat ; } 2>&1 | travisfoldblock "$1" ; }

    function traviscolordiagcmd() { { travis_color "$1" "${@:3}" ; "${@:3}" ; } 2>&1 | travisfoldblock "$2" ; }
    function travislogdiagcmd() { traviscolordiagcmd GREEEN "$@" ; }
    function traviserrdiagcmd()  { traviscolordiagcmd RED "$@" ; }

  - |
    # various util function
    function mkparentdir() { mkdir -p "$(realpath "$(dirname "$1")")" ; }

    function my_du() { du --max-depth=3 -h --time "$@" | awk -F '\t' '{OFS="\t"}{print $3, $2 $1}' | sort ; }

    function winexec { "$(realpath "$1")" "${@:2}" ; }

    function tr_yellow_title { echo -e "$YELLOW" "$@" ; }
    function tr_blue_title { echo -e "$YELLOW" "$@" ; }


before_script:
  - "tr_blue_title '##### before_script ######'"

  - |
    # unset sensitive information from variables to prevent printing them to output log
    unset QT_ACCOUNT_TOKEN


jobs:
  include:

    - name: windows
      os: windows
#      solution:
      env:
        - DOWNLOAD_DIR='C:\downloads'
        - QT_ONLINE_INSTALLER_URL='https://download.qt.io/archive/online_installers/3.2/qt-unified-windows-x86-3.2.3-online.exe'
        - QT_INSTALL_DIR='C:\Qt'
        - QT_INSTALL_MSVC_SUBDIR='5.9.9\msvc2015_64'
        - QT_INSTALL_PACKAGES='qt.qt5.599.win64_msvc2015_64'
        - CMAKE_PREFIX_PATH="${QT_INSTALL_DIR}\\${QT_INSTALL_MSVC_SUBDIR}"

        - MS_VS_CPP_BUILD_TOOLS_VERSION='14.0.25420.1'
#        - VC_BUILD_TOOLS_VERSION='2015.4' # https://chocolatey.org/packages/vcbuildtools/2015.4
        - WIX_TOOLSET_VERSION='3.11.1'

        - CMAKE_GENERATOR='Visual Studio 14 2015'
        - CMAKE_GENERATOR_PLATFORM='x64'
        - CMAKE_GENERATOR_TOOLSET='v140,host=x64'

        - Platform='X64'
#        - VCTargetsPath='C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140'
        - msbuild_path='C:\Program Files (x86)\MSBuild\14.0\Bin\amd64\MSBuild.exe'

      cache:
        directories:
          - "$DOWNLOAD_DIR"
          - "$QT_INSTALL_DIR"

      install:
        - "tr_blue_title '##### install ###### (jobs-include-install)'"

        - |
          # functions for install
          function cached() { [[ -e "$1" ]] && echo "### using cached '$1' ${2:+($2)}" ; }

        - |
          # install Qt (CMAKE_PREFIX_PATH)
          if ! cached "$CMAKE_PREFIX_PATH" 'CMake Qt MSVC prefix path'; then
            export QT_INSTALLER_PATH="${DOWNLOAD_DIR}\\${QT_ONLINE_INSTALLER_URL##*/}"

            travisfoldtitled 'get.Qt.online.installer' '### getting Qt online installer' < <(
              if ! cached "$QT_INSTALLER_PATH" 'Qt online installer'; then
                echo '### downloading Qt online installer'
                mkparentdir "$QT_INSTALLER_PATH"
                wget --progress=dot:giga "$QT_ONLINE_INSTALLER_URL" -O "$QT_INSTALLER_PATH"
              fi
            )

            travisfoldtitled 'set.Qt.account.login' '### setting Qt account login' < <(
              qt_account_ini_path="${APPDATA}\\Qt\\qtaccount.ini"
              mkparentdir "$qt_account_ini_path"
              printf '%s\n' '[QtAccount]' "email=$QT_ACCOUNT_LOGIN" "jwt=$QT_ACCOUNT_TOKEN" > "$qt_account_ini_path"
            )

            travisfoldtitled 'install.Qt' '### installing Qt dependencies using Qt online installer' < <(
              mkparentdir "$QT_INSTALL_DIR"
              "$(realpath "$QT_INSTALLER_PATH")" -v --script 'travis_windows\install-qt.qs' 2>&1 | tee ~/'install-qt.out' | awk 'NR<42||/QTCI/'
            )

            travisfoldtitled 'install.Qt.ensure.was.success' '### ensuring that Qt installation was sucessful' < <(
              [[ -d "$CMAKE_PREFIX_PATH" ]] || { echo '### !!! Error installing Qt' ; echo $_ >&2 ; cat ~/'install-qt.out' ; false ; }
            )
          fi

        - |
          travisfoldtitled 'Install.WindowsFeature.Net.Framework.Core' '### Install-WindowsFeature Net-Framework-Core' < <(
            powershell Install-WindowsFeature Net-Framework-Core
          )

        - | # Microsoft Visual C++ Build Tools 2015 14.0.25420.1  # https://chocolatey.org/packages/microsoft-visual-cpp-build-tools/14.0.25420.1
          travisfoldtitled 'Install.Microsoft.Visual.CPP.Build.Tools.2015' '### installing Microsoft Visual C++ Build Tools 2015 14.0.25420.1' < <(
            cinst microsoft-visual-cpp-build-tools --version "$MS_VS_CPP_BUILD_TOOLS_VERSION"
          )

        - | # WiX Toolset 3.11.1  # https://chocolatey.org/packages/wixtoolset/3.11.1
          travisfoldtitled 'Install.WiX.Toolset' '### installing WiX Toolset 3.11.1' < <(
            cinst wixtoolset --version "$WIX_TOOLSET_VERSION"
          )

      script:
        - "tr_blue_title '##### script ###### (jobs-include-windows-script)'"

        - mkdir 'build' && cd $_

        # cmake -G 'Visual Studio 14 2015' -A 'x64' -T 'v140,host=x64' -D 'CMAKE_BUILD_TYPE=Debug' '..'
        - |
          tr_yellow_title '### CMake generate'
          cmake -D 'CMAKE_BUILD_TYPE=Debug' '..'

        - |
          tr_yellow_title '### CMake build'
          cmake --build '.'

        # "C:/Program Files (x86)/MSBuild/14.0/Bin/amd64/MSBuild.exe' /p:Configuration=Debug /p:Platform=x64 /verbosity:diag
        - |
          tr_yellow_title '### MSBuild WIX installer'
          cd installer
          "$(realpath "$msbuild_path")" //p:Configuration=Debug //verbosity:diag



      after_script:
        - "tr_blue_title '##### after_script ###### (jobs-include-windows-after_script)'"

        - |
          which -a msbuild
          which -a MSBuild.exe
          where msbuild
          where.exe msbuild
          /c/Windows/System32/where.exe msbuild
          cmd /C 'where msbuild'
          true

      after_failure:
        - "tr_blue_title '##### after_failure ###### (jobs-include-windows-after_failure)'"

        - |
          cmake_output_log="${TRAVIS_BUILD_DIR}/build/CMakeFiles/CMakeOutput.log"
          echo "# $cmake_output_log :"
          cat "$cmake_output_log"

        - traviserrdiagcmd 'du.program.files.dirs.one' my_du 'C:\Program Files' 'C:\Program Files (x86)'
        - traviserrdiagcmd 'du.program.files.dirs.two' "my_du 'C:\Program Files' 'C:\Program Files (x86)'"


    - name: linux
      os: linux
      dist: xenial
      addons:
        apt:
          sources:
            - sourceline: 'ppa:lopin/git-buildpackage-backports'
          packages:
            - cmake make g++
            - libssl-dev libsodium-dev libcurl4-openssl-dev libavahi-compat-libdnssd-dev libsystemd-dev
            - xorg-dev libx11-dev libgl1-mesa-glx libegl1-mesa
            - qtbase5-dev qtdeclarative5-dev libqt5svg5-dev
            - dpkg-dev git-buildpackage fakeroot debhelper

      script:
        - "tr_blue_title '##### script ##### (jobs-include-linux-script)'"

        - |
          tr_yellow_title '### create debian/changelog from git history'
          gbp dch --ignore-branch

        - |
          tr_yellow_title '### make linux DEB package'
          dpkg-buildpackage -us -uc



after_script:
  - "tr_blue_title '##### after_script ######'"

  - du -h -d 1 ~ "$TRAVIS_BUILD_DIR"
  - find "$TRAVIS_BUILD_DIR" -print0 | xargs -0 ls -ld

  - traviserrdiagcmd 'find.from.root.one' find / -iname '*msbuild*' -print0 \| xargs -0 ls -ld
  - traviserrdiagcmd 'find.from.root.two' "find / -iname '*msbuild*' -print0 | xargs -0 ls -ld"

  - env


after_failure:
  - "tr_blue_title '##### after_failure ######'"

  - echo "# PWD=$PWD"
